# Site settings
title: Edo Prasetyo Nur Adi Wijaya
twitter_username: prasejaya
name: Edo Prasetyo Nur Adi Wijaya

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Email
   mailto : prasejaya@gmail.com
 - title: GitHub
   url: https://github.com/prasejaya
 - title: LinkedIn
   url: https://www.linkedin.com/in/edo-wijaya-22483254

#Any buzzword skills you want to include
skills:
 - PHP
 - Android Native
 - Kotlin
 - Python
 - SQL
 - REST
 - Technical Architecture
 - Firebase
 - Machine learning
 - Cold Fusion

#Work experience is required
roles:
 - title: Full Stack Developer
   start: Dec 2018
   end: Ongoing
   employer: Kokola
   description: Kokola is a manufacture company with total employees about 2000 people. <br/>Modifying cold fusion as client request in ERP system, develop android & PHP application for operational support.<br/> Design API system for operational purpose.
 - title: Junior Developer
   start: May 2018
   end: Dec 2018
   employer: ITTRON
   description: ITTRON is software house which create online shop application. <br/> Customize online shop as client request.
 - title: Junior Developer
   start: Jan 2014
   end: May 2018
   employer: Sentra Vidya Utama (Sevima)
   description: Sevima is software house which create education application.<br/> Maintenance backend website for education application.

#Education is required
education:
 - level: Sarjana Komputer (S.Kom)
   date: 2013
   subject: Informatics
   school: Institut Teknologi Adhi Tama Surabaya (ITATS).


intro: |
  I am an engineer with 6 years experience working in technology. I have primarily worked on the PHP with their framework. <br/> I also have knowledge about some other area. I have created android application using android native and kotlin.<br/> Currently, i use cold fusion to build ERP system. 
  I am also build machine learning with python.  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap. I have also worked with variou php framework such as code igniter, laravel and cake php)<br/><br/>
   <strong>Mobile Application</strong>: I have a good knowledge of mobile application life-cycle management. I have created mobile application with java, cordova, framework 7 and kotlin. <br/><br/>
   <strong>Machine Learning</strong>: In this area, i have create application for image recognition for javanese letter and currently, i am developing website using flask.<br/><br/>
   Stay curious & stay hungry is my vision. I believe by create application i can reach my dreams. <br/><br/>
 
